allowed_domains:
  - gitlab.com/cgcovid/dados-abertos
  - dadosabertos.saude.gov.br
  - gov.br/saude
  - infoms.saude.gov.br
  - fiocruz.br
  - github.com/infogripe
  - agenciagov.ebc.com.br
  - agenciabrasil.ebc.com.br
  - paho.org
  - who.int
  - g1.globo.com
  - cnnbrasil.com.br
  - folha.uol.com.br
  - estadao.com.br
  - uol.com.br
  - metropoles.com
  - exame.com
  - revistapesquisa.fapesp.br
  - cienciahoje.org.br
  - sbmt.org.br
